container_image = ???

executable      = example.R
arguments       = $(station_id)

transfer_input_files = my_functions.R, osdf:///aws-opendata/us-east-1/noaa-ghcn-pds/csv/by_station/$(station_id).csv
transfer_output_remaps = "$(station_id).png=results/$(station_id).png"

log    = logs/example.$(Cluster).log
output = logs/$(station_id).out
error  = logs/$(station_id).err

request_cpus   = 1
request_memory = 4GB
request_disk   = 4GB

queue station_id from (
    USW00014837
)
