container_image = osdf:///ospool/uc-shared/public/OSG-Staff/training/tidyverse.sif

executable      = Rscript example.R $(station_id)

transfer_input_files = example.R, my_functions.R, data/$(station_id).csv
transfer_output_remaps = "$(station_id).png=results/$(station_id).png"
should_transfer_files = YES

log    = logs/example.$(Cluster).log
output = logs/$(station_id).out
error  = logs/$(station_id).err

request_cpus   = 1
request_memory = 2GB
request_disk   = 2GB

queue station_id from (
    USW00014837
)
